### PR TITLE
Always expand charts to a dir for loading

### LINKED ISSUE #111: Protect against charts with duplicate files
We noticed that some charts upstream may come with duplicate files in them, including the `values.yaml` that the CLI relo8ks (or the API) is rewriting.

While this is an error upstream, it does not make sense to have duplicate files with the same filename in the chart tarball, relok8s behavior makes things worse downstream because:
- The behavior is different if the chart is still in a tgz file, or deflated before on a directory.
- The issue is not noticed while running the tool.

When a deflated chart is used, the tool works, because any duplicated file gets collapsed into its latest occurrence in the tarball.

When a tgz is used directly, **relok8s updates only the first occurrence it encounters of the values files, but when the relocated tar is deflated the latest non modified version is used instead**. And users will not notice unless they inspect the YAMLs.

This issue is to:
- ~Detect and remove duplicates from loaded charts~.
- ~Upon duplicate detection the issues are reported in the log~.

~At some point we might decide whether we want to fail by default if there are duplicate entries in the input chart. In such case we might want to provide a way to force consumption of broken charts, in case the end user may need that~.

The above was difficult to justify to end users. It is much simpler to make the file tarred behavior be the same as the deflated directory one: just use the latest version on each file on the tar. That is actually what you'd expect even if the upstream chart tar contains duplicate,s the latest one should be the updated version, usually.

### PR DESCRIPTION
**Pull request by josvazg**
Signed-off-by: Jose Luis Vazquez Gonzalez <josvaz@vmware.com>

So that we get the same behavior whether we get a tar.gz tarball or a extracted chart folder. In particular, if the tgz has replicated files, we will be only using the latest in the tarball sequence for that filename.

Closes #111

Note this is a bit more complex than initially expected because the chart tarball does not have a well known root directory. The chart name needs to be detected so we can point the loader to the `{chartname}/Chart.yaml` inside such directory.
See: https://v2.helm.sh/docs/developing_charts/#the-chart-file-structure
> A chart is organized as a collection of files inside of a directory. The directory name is the name of the chart (without versioning information). Thus, a chart describing WordPress would be stored in the wordpress/ directory.

### CODE REVIEW

File: pkg/mover/chart.go [hunk 1]
```diff
@@ -255,13 +256,55 @@ func (cm *ChartMover) loadChartFromIntermediateBundle(bundlePath string) error {
...
+		}
+		if err := untarz(true, path, "*", tmpdir); err != nil {
+			return fmt.Errorf("failed to extract chart: %w", err)
+		}
+		chartname, err := detectChartName(tmpdir)
+		if err != nil {
+			return fmt.Errorf("failed to detect chartname from extracted chart: %w", err)
+		}
+		dir = filepath.Join(tmpdir, chartname)
+	}
```
Comment (migmartri) [inline pkg/mover/chart.go:283]: extra separation line here please?

File: pkg/mover/chart.go [hunk 2]
```diff
@@ -255,13 +256,55 @@ func (cm *ChartMover) loadChartFromIntermediateBundle(bundlePath string) error {
...
-	if cm.chart, err = loader.Load(path); err != nil {
-		return &ChartLoadingError{Path: path, Inner: err}
+	// always unpack the chart tarball to a directory to avoid issues loading
+	// files if the tgz contains replicated entries
+	dir := path
+	info, err := os.Stat(path)
+	if err != nil {
+		return &ChartLoadingError{Path: dir, Inner: err}
+	}
+	if !info.IsDir() {
```
Comment (migmartri) [inline pkg/mover/chart.go:266]: This seems like a good candidate to its own function.

File: pkg/mover/chart.go [hunk 3]
```diff
@@ -255,13 +256,55 @@ func (cm *ChartMover) loadChartFromIntermediateBundle(bundlePath string) error {
 
 // loadChartFromPath load the chart in memory from a given path
 func (cm *ChartMover) loadChartFromPath(path string) error {
-	var err error
-	if cm.chart, err = loader.Load(path); err != nil {
-		return &ChartLoadingError{Path: path, Inner: err}
+	// always unpack the chart tarball to a directory to avoid issues loading
+	// files if the tgz contains replicated entries
```
Comment (migmartri) [inline pkg/mover/chart.go:260]: could you add a link to the issue with duplicates?

File: pkg/mover/chart.go [hunk 4]
```diff
@@ -255,13 +256,55 @@ func (cm *ChartMover) loadChartFromIntermediateBundle(bundlePath string) error {
...
 	}
 	return nil
 }
 
+func detectChartName(chartdir string) (string, error) {
+	d, err := os.Open(chartdir)
+	if err != nil {
+		return "", fmt.Errorf("failed to open chart dir: %w", err)
+	}
+	files, err := d.Readdir(1)
```
Comment (migmartri) [inline pkg/mover/chart.go:295]: should we check that only has one file inside?

File: pkg/mover/chart.go [hunk 5]
```diff
@@ -255,13 +256,55 @@ func (cm *ChartMover) loadChartFromIntermediateBundle(bundlePath string) error {
...
+			return fmt.Errorf("failed to detect the chart directory name: %w", err)
+		}
+		if err := untarz(true, path, "*", tmpdir); err != nil {
+			return fmt.Errorf("failed to extract chart: %w", err)
+		}
+		chartname, err := detectChartName(tmpdir)
+		if err != nil {
+			return fmt.Errorf("failed to detect chartname from extracted chart: %w", err)
+		}
+		dir = filepath.Join(tmpdir, chartname)
```
Comment (migmartri) [inline pkg/mover/chart.go:282]: is there any way to implement the equivalent to strip components?

```
$ tar xzf wordpress-12.2.4.tgz --strip-components=1
$ ls
Chart.lock  charts  Chart.yaml  ci  README.md  templates  values.schema.json  values.yaml  wordpress-12.2.4.tgz
```

File: pkg/mover/tar.go [hunk 6]
```diff
@@ -74,23 +75,17 @@ func (tfw *tarFileWriter) WriteIOFile(name string, size int64, r io.Reader, perm
...
-	if tarPath == "" {
-		pathPrefix = "*"
-	}
-	f, err := os.Open(tarFile)
-	if err != nil {
-		return fmt.Errorf("failed to open tar file %s: %w", tarFile, err)
-	}
-	defer f.Close()
-	tr := tar.NewReader(f)
+	return untarz(false /*gunzip*/, tarFile, tarPath, dstDir)
```
Comment (migmartri) [inline pkg/mover/tar.go:78]: `/*gunzip*/`

What's this?

File: pkg/mover/chart.go (hunk 2 above)
Comment (josvazg) [reply pkg/mover/chart.go:266]: yep, the only caveat is that defer to remove the tempdir... but I will find a way.

File: pkg/mover/chart.go (hunk 1 above)
Comment (josvazg) [reply pkg/mover/chart.go:283]: ok

File: pkg/mover/chart.go (hunk 3 above)
Comment (josvazg) [reply pkg/mover/chart.go:260]: you mean a JIRA link here?

File: pkg/mover/chart.go (hunk 4 above)
Comment (josvazg) [reply pkg/mover/chart.go:295]: maybe, for completeness

File: pkg/mover/chart.go (hunk 5 above)
Comment (josvazg) [reply pkg/mover/chart.go:282]: we agreed offline not to go there

File: pkg/mover/tar.go [hunk 7]
```diff
@@ -170,3 +165,28 @@ func newTarInTarOpener(tarFile, tarInTarFile string) func() (io.ReadCloser, erro
 		return openFromTar(tarFile, tarInTarFile)
 	}
 }
+
+func untarz(gunzip bool, tarzFile, tarPath, dstDir string) error {
```
[the remark this answers is not in the document]
Comment (josvazg) [reply pkg/mover/tar.go:169]: this will go away and will use the expand from helm library

File: pkg/mover/tar.go (hunk 6 above)
Comment (josvazg) [reply pkg/mover/tar.go:78]: will go away as well

File: pkg/mover/chart.go (hunk 2 above)
Comment (josvazg) [reply pkg/mover/chart.go]: think it is now much better

File: pkg/mover/chart.go (hunk 3 above)
Comment (josvazg) [reply pkg/mover/chart.go]: ah ok!

adding...

Comment (josvazg) [reply pkg/mover/chart.go]: done now

File: pkg/mover/chart.go (hunk 4 above)
Comment (josvazg) [reply pkg/mover/chart.go]: done as well

File: pkg/mover/tar.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (josvazg) [reply pkg/mover/tar.go]: done

File: pkg/mover/tar.go (hunk 6 above)
Comment (josvazg) [reply pkg/mover/tar.go]: done

File: pkg/mover/chart.go [hunk 8]
```diff
@@ -256,12 +257,68 @@ func (cm *ChartMover) loadChartFromIntermediateBundle(bundlePath string) error {
 // loadChartFromPath load the chart in memory from a given path
 func (cm *ChartMover) loadChartFromPath(path string) error {
 	var err error
-	if cm.chart, err = loader.Load(path); err != nil {
-		return &ChartLoadingError{Path: path, Inner: err}
+	dir := path
+	if isChartFile(path) {
```
Comment (migmartri) [inline pkg/mover/chart.go:261]: well, this method is not saying that's a chart tarball, it's saying that's not a directory right?

File: pkg/mover/chart.go [hunk 9]
```diff
@@ -256,12 +257,68 @@ func (cm *ChartMover) loadChartFromIntermediateBundle(bundlePath string) error {
...
+		// always unpack the chart tarball to a directory to avoid issues loading
+		// files if the tgz contains replicated entries
+		// https://github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes/issues/111
+		if dir, err = expandedChartDir(path); err != nil {
```
Comment (migmartri) [inline pkg/mover/chart.go:265]: why don't you just override the path here?

You are not adding any protection by having two variables since you are setting one as the other

File: pkg/mover/chart.go [hunk 10]
```diff
@@ -256,12 +257,68 @@ func (cm *ChartMover) loadChartFromIntermediateBundle(bundlePath string) error {
...
+	return err == nil && !info.IsDir()
+}
+
+func expandedChartDir(path string) (string, error) {
+	tmpdir, err := os.MkdirTemp("", "expanded-chart-*")
+	if err != nil {
+		return "", fmt.Errorf("failed to make temporary directory: %w", err)
+	}
+
+	if err := chartutil.ExpandFile(tmpdir, path); err != nil {
```
Comment (migmartri) [inline pkg/mover/chart.go:288]: add a comment explaining that this method does please

File: pkg/mover/chart.go [hunk 11]
```diff
@@ -256,12 +257,68 @@ func (cm *ChartMover) loadChartFromIntermediateBundle(bundlePath string) error {
...
+func detectChartName(chartdir string) (string, error) {
+	d, err := os.Open(chartdir)
+	if err != nil {
+		return "", fmt.Errorf("failed to open chart dir: %w", err)
+	}
+	files, err := d.Readdir(2)
+	if err != nil {
+		return "", fmt.Errorf("failed to list chart dir: %w", err)
+	}
+	if len(files) < 1 {
```
Comment (migmartri) [inline pkg/mover/chart.go:310]: what about len(files) != 1 and just a simple error message?

File: pkg/mover/chart.go [hunk 12]
```diff
@@ -256,12 +257,68 @@ func (cm *ChartMover) loadChartFromIntermediateBundle(bundlePath string) error {
...
+
+	chartname, err := detectChartName(tmpdir)
+	if err != nil {
+		return "", fmt.Errorf("failed to detect chartname from extracted chart: %w", err)
+	}
+	return filepath.Join(tmpdir, chartname), nil
+}
+
+// detectChartName expects chartdir to contain a single subdirectory, matching
+// the chartname
```
Comment (migmartri) [inline pkg/mover/chart.go:300]: I'd elaborate a little bit more, explaining that a justs extracted Helm chart usually contains a directory in the root called with the name of the chart.

**Review by migmartri — COMMENTED** [review]
Great! It should not be so difficult to add some unit tests here,

File: pkg/mover/chart.go (hunk 8 above)
Comment (josvazg) [reply pkg/mover/chart.go:261]: to be picky yes, it could be a link or something else... but then the file extract will fail it is not a tarball

File: pkg/mover/chart.go (hunk 9 above)
Comment (josvazg) [reply pkg/mover/chart.go:265]: Usually linters and such frown upon method or function inputs mutated inside. And for good reason, because you maybe changing the invariants on the code in ways that might be not be clear, or even lead to bugs.
- In this method `path` is the input **path** given originally, which _could be a tarball or a directory_.
- On the other hand `dir` is the directory in which files are already expanded, can be original or temporary.
Also this way we never lose track of the original path, when `dir` differs.

File: pkg/mover/chart.go (hunk 10 above)
Comment (josvazg) [reply pkg/mover/chart.go:288]: ok

File: pkg/mover/chart.go (hunk 11 above)
Comment (josvazg) [reply pkg/mover/chart.go:310]: OK, I can join those I guess

File: pkg/mover/chart.go (hunk 12 above)
Comment (josvazg) [reply pkg/mover/chart.go:300]: I can link to the helm chart docs, in fact I thought I had done it...

File: pkg/mover/chart.go (hunk 8 above)
Comment (josvazg) [reply pkg/mover/chart.go:261]: changed to `if !isChartDir(path) {`

File: pkg/mover/chart.go (hunk 10 above)
Comment (josvazg) [reply pkg/mover/chart.go:290]: done

File: pkg/mover/chart.go (hunk 12 above)
Comment (josvazg) [reply pkg/mover/chart.go:302]: done

File: pkg/mover/chart.go (hunk 11 above)
Comment (josvazg) [reply pkg/mover/chart.go:313]: done

**Review by migmartri — APPROVED** [review]
LGTM!
